CONTAINER_NAME="percona-mysql"
ROOT_PASSWORD="x3h3Ays7dNdUGkYVKyDEMkHVEUeFyDr8"
SERVICE_PATH="/var/docker/mysql-percona"
DATA_PATH="/var/docker/mysql-percona/data"
CONFIG_PATH="/var/docker/mysql-percona/config"
NETWORK="main"
VERSION="8.0"